blank_issues_enabled: false
contact_links:
  - name: XinWiki Documentation
    url: https://github.com/Tencent/XinWiki/blob/main/docs/QA.md
    about: Check XinWiki FAQ
  - name: Discussions
    url: https://github.com/Tencent/XinWiki/discussions
    about: Ask questions or share ideas in Discussions
