package generator

import (
	"context"
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/chromedp/cdproto/page"
	"github.com/chromedp/chromedp"

	"github.com/Tencent/XinWiki/internal/types"
)

// ReportGenerator produces a structured PDF report. It first delegates to
// the MarkdownGenerator to get Markdown content, then renders the Markdown
// into a styled HTML document and prints it to PDF via headless Chrome
// (chromedp).
type ReportGenerator struct {
	mdGen *MarkdownGenerator
}

func NewReportGenerator() *ReportGenerator {
	return &ReportGenerator{mdGen: NewMarkdownGenerator()}
}

func (g *ReportGenerator) Type() types.ArtifactType { return types.ArtifactTypeReport }

func (g *ReportGenerator) Generate(ctx context.Context, in *Input) (*Result, error) {
	// Step 1: get Markdown content from the LLM using the markdown
	// generator with a "report-oriented" prompt twist.
	mdIn := *in
	mdIn.Prompt = buildReportPrompt(in)
	mdRes, err := g.mdGen.Generate(ctx, &mdIn)
	if err != nil {
		return nil, err
	}
	mdContent := string(mdRes.Bytes)

	// Step 2: render to HTML, then to PDF.
	html := reportHTMLTemplate(in.Artifact.Title, mdContent, in.Language)
	pdfBytes, pageCount, err := htmlToPDF(ctx, html)
	if err != nil {
		return nil, fmt.Errorf("report: render PDF: %w", err)
	}
	return &Result{
		MIMEType:      "application/pdf",
		FileExtension: "pdf",
		Bytes:         pdfBytes,
		ExtraMetadata: map[string]any{
			"page_count":   pageCount,
			"markdown_len": len(mdContent),
		},
	}, nil
}

func buildReportPrompt(in *Input) string {
	var b strings.Builder
	b.WriteString(in.Prompt)
	b.WriteString("\n\n请以正式研究报告的形式输出：")
	b.WriteString("\n- 包含封面标题、摘要、目录（用Markdown列章节）、正文、结论、参考来源；")
	b.WriteString("\n- 使用 H1/H2/H3 构建清晰层次；")
	b.WriteString("\n- 正文中可以使用表格对比要点；")
	b.WriteString("\n- 字数控制在 2000-5000 字之间。")
	return b.String()
}

func reportHTMLTemplate(title, markdown, lang string) string {
	tmpl := `<!doctype html><html lang="%s"><head><meta charset="utf-8"><title>%s</title>
<style>
@page { size: A4; margin: 22mm 18mm 22mm 18mm; }
body { font-family: -apple-system, "Helvetica Neue", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", Arial, sans-serif; font-size: 11.5pt; line-height: 1.65; color: #1d1d1f; }
h1 { font-size: 24pt; margin: 0 0 14pt 0; border-bottom: 2px solid #007aff; padding-bottom: 6pt; }
h2 { font-size: 16pt; margin: 22pt 0 8pt; color: #007aff; }
h3 { font-size: 13pt; margin: 14pt 0 6pt; }
p  { margin: 0 0 8pt; text-align: justify; }
ul,ol { margin: 0 0 8pt; padding-left: 22pt; }
li { margin: 2pt 0; }
blockquote { border-left: 3px solid #c7c7cc; padding: 4pt 12pt; margin: 8pt 0; color: #555; background: #f6f6f6; border-radius: 0 6pt 6pt 0; }
table { width: 100%%; border-collapse: collapse; margin: 8pt 0; font-size: 10.5pt; }
th,td { border: 1px solid #d1d1d6; padding: 5pt 8pt; }
th { background: #f2f2f7; text-align: left; }
code { font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 10pt; background: #f2f2f7; padding: 1pt 4pt; border-radius: 3pt; }
.cover { text-align: center; padding-top: 80mm; page-break-after: always; }
.cover h1 { font-size: 30pt; border: none; }
.cover .meta { color: #8e8e93; margin-top: 16pt; font-size: 12pt; }
</style></head><body>
<section class="cover"><h1>%s</h1><div class="meta">Generated by XinWiki</div></section>
<article>%s</article>
</body></html>`
	// Minimal markdown -> HTML (we don't need a full MD parser here; rely on
	// plain text with paragraph breaks. For production, add blackfriday/lute).
	htmlBody := simpleMarkdownToHTML(markdown)
	if title == "" {
		title = "Report"
	}
	if lang == "" {
		lang = "zh"
	}
	return fmt.Sprintf(tmpl, lang, escapeHTML(title), escapeHTML(title), htmlBody)
}

// simpleMarkdownToHTML is a minimal Markdown → HTML converter sufficient for
// headings/lists/tables/blockquotes/code. It is deliberately narrow; if the
// LLM outputs more exotic constructs (links, images) they are rendered as
// plain text.
func simpleMarkdownToHTML(md string) string {
	var out strings.Builder
	lines := strings.Split(md, "\n")
	inList := false
	listType := ""
	for i := 0; i < len(lines); i++ {
		line := lines[i]
		trim := strings.TrimRight(line, " \t")
		// Headings
		switch {
		case strings.HasPrefix(trim, "### "):
			closeList(&out, &inList)
			fmt.Fprintf(&out, "<h3>%s</h3>", inlineMD(strings.TrimPrefix(trim, "### ")))
		case strings.HasPrefix(trim, "## "):
			closeList(&out, &inList)
			fmt.Fprintf(&out, "<h2>%s</h2>", inlineMD(strings.TrimPrefix(trim, "## ")))
		case strings.HasPrefix(trim, "# "):
			closeList(&out, &inList)
			fmt.Fprintf(&out, "<h1>%s</h1>", inlineMD(strings.TrimPrefix(trim, "# ")))
		case strings.HasPrefix(trim, "> "):
			closeList(&out, &inList)
			fmt.Fprintf(&out, "<blockquote>%s</blockquote>", inlineMD(strings.TrimPrefix(trim, "> ")))
		case strings.HasPrefix(trim, "- ") || strings.HasPrefix(trim, "* "):
			if !inList || listType != "ul" {
				closeList(&out, &inList)
				out.WriteString("<ul>")
				inList = true
				listType = "ul"
			}
			fmt.Fprintf(&out, "<li>%s</li>", inlineMD(trim[2:]))
		case len(trim) > 1 && trim[0] >= '0' && trim[0] <= '9' && (trim[1] == '.' || (trim[1] >= '0' && trim[1] <= '9' && len(trim) > 2 && trim[2] == '.')):
			// crude ordered list detection
			dot := strings.Index(trim, ". ")
			if dot > 0 {
				if !inList || listType != "ol" {
					closeList(&out, &inList)
					out.WriteString("<ol>")
					inList = true
					listType = "ol"
				}
				fmt.Fprintf(&out, "<li>%s</li>", inlineMD(trim[dot+2:]))
			} else {
				closeList(&out, &inList)
				out.WriteString("<p>")
				out.WriteString(inlineMD(trim))
				out.WriteString("</p>")
			}
		case trim == "":
			closeList(&out, &inList)
		default:
			closeList(&out, &inList)
			out.WriteString("<p>")
			out.WriteString(inlineMD(trim))
			out.WriteString("</p>")
		}
	}
	closeList(&out, &inList)
	return out.String()
}

func closeList(out *strings.Builder, inList *bool) {
	if *inList {
		out.WriteString("</ul>")
		*inList = false
	}
}

func inlineMD(s string) string {
	s = escapeHTML(s)
	// Bold **x**
	s = replacePairs(s, "**", "<strong>", "</strong>")
	// Italic *x* (avoid conflict with bold by using single-star pairs after bold)
	s = replacePairs(s, "*", "<em>", "</em>")
	// Inline code `x`
	s = replacePairs(s, "`", "<code>", "</code>")
	return s
}

func replacePairs(s, delim, open, close string) string {
	var b strings.Builder
	for {
		idx := strings.Index(s, delim)
		if idx < 0 {
			b.WriteString(s)
			break
		}
		b.WriteString(s[:idx])
		rest := s[idx+len(delim):]
		idx2 := strings.Index(rest, delim)
		if idx2 < 0 {
			b.WriteString(s[idx:])
			break
		}
		b.WriteString(open)
		b.WriteString(rest[:idx2])
		b.WriteString(close)
		s = rest[idx2+len(delim):]
	}
	return b.String()
}

func escapeHTML(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;")
	return r.Replace(s)
}

// htmlToPDF spins up a chromedp context (reusing the same allocator approach
// used in web_fetch) and prints the given HTML document to PDF bytes.
func htmlToPDF(ctx context.Context, html string) ([]byte, int, error) {
	// Encode HTML as a data URL.
	encoded := base64.StdEncoding.EncodeToString([]byte(html))
	dataURL := "data:text/html;base64," + encoded

	execCtx, cancel := context.WithTimeout(ctx, 60*time.Second)
	defer cancel()

	// chromedp options: run headless with no sandbox for container deployments.
	opts := append(chromedp.DefaultExecAllocatorOptions[:],
		chromedp.Flag("headless", true),
		chromedp.Flag("disable-gpu", true),
		chromedp.Flag("no-sandbox", true),
		chromedp.Flag("disable-dev-shm-usage", true),
	)
	allocCtx, cancelAlloc := chromedp.NewExecAllocator(execCtx, opts...)
	defer cancelAlloc()
	browserCtx, cancelBrowser := chromedp.NewContext(allocCtx)
	defer cancelBrowser()

	var pdfBuf []byte
	if err := chromedp.Run(browserCtx,
		chromedp.Navigate(dataURL),
		chromedp.WaitReady("body", chromedp.ByQuery),
		chromedp.ActionFunc(func(ctx context.Context) error {
			// Wait for reflow/fonts to settle.
			time.Sleep(500 * time.Millisecond)
			return nil
		}),
		chromedp.EmulateViewport(1024, 1448),
		chromedp.FullScreenshot(nil, 0), // warm up layout
		chromedp.ActionFunc(func(ctx context.Context) error {
			var err error
			pdfBuf, _, err = page.PrintToPDF().
				WithPaperWidth(8.27).WithPaperHeight(11.69).
				WithMarginTop(0.87).WithMarginBottom(0.87).
				WithMarginLeft(0.7).WithMarginRight(0.7).
				Do(ctx)
			return err
		}),
	); err != nil {
		return nil, 0, err
	}
	// Estimate page count from PDF bytes: very rough /Page count marker.
	pages := estimatePDFPages(pdfBuf)
	_ = pages
	return pdfBuf, pages, nil
}

func estimatePDFPages(b []byte) int {
	n := 0
	for _, token := range []string{"/Type /Page", "/Type/Page"} {
		n += strings.Count(string(b), token)
	}
	if n < 1 {
		n = 1
	}
	return n
}
