#!/usr/bin/env python3
"""Generate the build-offline-package.sh script."""
import os

lines = []
def w(s=""):
    lines.append(s)

w('#!/bin/bash')
w('# ==============================================================================')
w('# XinWiki 离线部署包构建脚本')
w('# ==============================================================================')
w('#')
w('# 用途:')
w('#   在 Linux amd64 服务器上运行，构建 XinWiki 项目所有自定义 Docker 镜像，')
w('#   拉取第三方基础镜像，并打包成完整的离线部署包')
w('#   (xinwiki-offline-deploy-amd64.tar.gz)。')
w('#')
w('# 用法:')
w('#   ./scripts/build-offline-package.sh              # 构建所有镜像并打包')
w('#   ./scripts/build-offline-package.sh --ui          # 仅构建前端镜像')
w('#   ./scripts/build-offline-package.sh --app         # 仅构建后端镜像')
w('#   ./scripts/build-offline-package.sh --docreader   # 仅构建文档解析镜像')
w('#   ./scripts/build-offline-package.sh --sandbox     # 仅构建沙箱镜像')
w('#   ./scripts/build-offline-package.sh --ui --app    # 构建指定多个镜像')
w('#   ./scripts/build-offline-package.sh --skip-frontend-build  # 跳过前端 dist 构建')
w('#   ./scripts/build-offline-package.sh --skip-pull-base       # 跳过拉取第三方基础镜像')
w('#   ./scripts/build-offline-package.sh --apt-mirror http://mirrors.tuna.tsinghua.edu.cn  # 指定 docreader apt 镜像')
w('#   ./scripts/build-offline-package.sh --help        # 显示帮助')
w('#')
w('# 环境要求:')
w('#   - Linux amd64 (x86_64)')
w('#   - Docker 已安装并运行')
w('#   - Git (用于获取 commit ID)')
w('#   - Node.js + npm (构建前端静态资源，除非使用 --skip-frontend-build)')
w('#   - Go (用于获取 Go 版本信息)')
w('#')
w('# 输出:')
w('#   - docker/images/amd64/xinwiki-ui.tar')
w('#   - docker/images/amd64/xinwiki-app.tar')
w('#   - docker/images/amd64/xinwiki-docreader.tar')
w('#   - docker/images/amd64/xinwiki-sandbox.tar')
w('#   - docker/images/amd64/paradedb.tar')
w('#   - docker/images/amd64/redis.tar')
w('#   - docker/images/amd64/nginx.tar')
w('#   - docker/images/amd64/SHA256SUMS')
w('#   - xinwiki-offline-deploy-amd64.tar.gz (最终离线部署包)')
w('#')
w('# ==============================================================================')
w('')
w('set -e')
w('')
w('# ------------------------------------------------------------------------------')
w('# 颜色定义')
w('# ------------------------------------------------------------------------------')
w("RED='\\033[0;31m'")
w("GREEN='\\033[0;32m'")
w("YELLOW='\\033[1;33m'")
w("BLUE='\\033[0;34m'")
w("NC='\\033[0m' # 无颜色")
w('')
w('# ------------------------------------------------------------------------------')
w('# 路径变量')
w('# ------------------------------------------------------------------------------')
w('SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"')
w('PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"')
w('IMAGE_OUTPUT_DIR="$PROJECT_ROOT/docker/images/amd64"')
w('')
w('cd "$PROJECT_ROOT"')
w('')
w('# ------------------------------------------------------------------------------')
w('# 日志函数')
w('# ------------------------------------------------------------------------------')
w("print_info()    { echo -e \"${BLUE}[INFO]${NC}  $1\"; }")
w("print_ok()      { echo -e \"${GREEN}[OK]${NC}    $1\"; }")
w("print_warn()    { echo -e \"${YELLOW}[WARN]${NC}  $1\"; }")
w("print_error()   { echo -e \"${RED}[ERROR]${NC} $1\"; }")
w("print_step()    { echo -e \"${BLUE}========== $1 ==========${NC}\"; }")
w('')
w('# ------------------------------------------------------------------------------')
w('# 帮助信息')
w('# ------------------------------------------------------------------------------')
w('show_help() {')
w('    echo "XinWiki 离线部署包构建脚本"')
w('    echo ""')
w('    echo "用法: $0 [选项]"')
w('    echo ""')
w('    echo "选项:"')
w('    echo "  --ui              仅构建前端镜像 (xinwiki-ui)"')
w('    echo "  --app             仅构建后端镜像 (xinwiki-app)"')
w('    echo "  --docreader       仅构建文档解析镜像 (xinwiki-docreader)"')
w('    echo "  --sandbox         仅构建沙箱镜像 (xinwiki-sandbox)"')
w('    echo "  --skip-frontend-build  跳过前端 dist 构建 (假设 frontend/dist 已存在)"')
w('    echo "  --skip-pull-base  跳过拉取第三方基础镜像 (paradedb, redis, nginx)"')
w('    echo "  --apt-mirror URL  指定 docreader 构建时的 apt 镜像源"')
w('    echo "  -h, --help        显示此帮助信息"')
w('    echo ""')
w('    echo "不带参数时默认构建所有镜像、拉取第三方基础镜像并打包离线部署包。"')
w('    exit 0')
w('}')
w('')

# Write part 1 to file
output_path = '/Users/tohnee/Trae/github/xinwiki-new/scripts/build-offline-package.sh'
with open(output_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Part 1 written: {len(lines)} lines")
